spring.application.name=MicroService
spring.datasource.url=jdbc:h2:mem:accountDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=""
spring.datasource.password=""
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
